language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get install swig
  - wget http://www.phontron.com/kytea/download/kytea-0.4.7.tar.gz
  - tar zxf kytea-0.4.7.tar.gz
  - pushd kytea-0.4.7 && ./configure && make && sudo make install && popd
  - rm -r kytea-0.4.7
  - sudo ldconfig

install:
  - make
  - make install

script:
  - make test
